version: "3.8"

services:
  hes-test-task:
    image: hes-test-task:latest
    pull_policy: never
    build: .
    container_name: "hes-test-task"
    volumes:
      - hes-test-task-mvnw_volume:/root/.m2
    ports:
      - "8080:8080"
    env_file:
      - .env
    environment:
      DB_URL: "${DB_URL}"
      DB_USER: "${DB_USER}"
      DB_PASS: "${DB_PASS}"
    depends_on:
      psqldb:
        condition: service_healthy

  psqldb:
    image : postgres:15-alpine
    container_name: "postgresql"
    volumes:
      - hes-test-task-db_volume:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    env_file:
      - .env
    environment:
      POSTGRES_DB: "hestesttask"
      POSTGRES_USER: "${DB_USER}"
      POSTGRES_PASSWORD: "${DB_PASS}"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $$POSTGRES_USER -d $$POSTGRES_DB"]
      interval: 10s
      retries: 5
      start_period: 30s
      timeout: 10s

volumes:
  hes-test-task-mvnw_volume:
  hes-test-task-db_volume: