spring:
  datasource:
    url: ${DB_URL}
    username: ${DB_USER}
    password: ${DB_PASS}
  jpa:
    generate-ddl: true
    defer-datasource-initialization: true
  sql:
    init:
      mode: always

rsa:
  private-key: classpath:certs/private.pem
  public-key: classpath:certs/public.pem

server:
  servlet:
    context-path: /api
